name: 'Build a Quarkus native application'
description: 'Build a Quarkus native application'
branding:
  icon: 'box'
  color: 'yellow'
inputs:
  outputName:
    description: name of the resulting executable binary file
    required: true
  dockerfilePath:
    description: 'relative path to the Dockerfile you want to use - leave blank for default'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile' 
  args: 
    - ${{ inputs.outputName }}
    - ${{ inputs.dockerfilePath }}
