name: 'Build Quarkus native image'
description: 'Build Quarkus native image'
inputs:
  dockerfilePath:
    description: 'relative path to the Dockerfile you want to use - leave blank for default'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile' 
  args: 
    - ${{ inputs.dockerfilePath }}
